### ISSUE TITLE
Switching between saved codes can result in overwriting

### ISSUE THREAD

**Issue by Michaeasmith** [robotmoose/robotmoose#74]
In the code editor, sometimes if you switch between two saved codes and hit "Run" while the dropdown menu is still selected, one of the codes will be overwritten by the other. 

I haven't figured out yet the exact combination of actions to reproduce this every time.

**Comment by Michaeasmith** [comment]
I have discovered that this bug can be reproduced without even pressing "Run". Simply switching from one saved code to another and then clicking elsewhere (so that the dropdown is no longer highlighted) can result in overwriting one of the codes. 

If you watch the dropdown, when you switch between codes and then click elsewhere it jumps back and forth between them before settling on one. It seems almost random which one it settles on, but the code itself does not change.

Has anyone else encountered this? It is very, very easy for me to overwrite code, and I have done it multiple times on purpose and by accident.

**Comment by mrmoss** [comment]
I'm having a hard time reproducing this bug. This was a known issue at the workshop, but it was fixed.

Where can you reproduce this (robotmoose.com, test.robotmoose.com, localhost)?

Is your robotmoose.com cached by chance?

**Comment by Michaeasmith** [comment]
I can reproduce it both on localhost (git freshly pulled, superstar freshly made) and robotmoose.com. I cleared cache on both and it still happens for me. Sometimes it takes about a dozen times switching between 2 codes and clicking away from the dropdown (or hitting Run), and sometimes it happens right away.

If the two code names are different in length, I see almost every time that the name of the other code flashes for an instant when you click Run or click away.

**Comment by mrmoss** [comment]
You're running Chrome on Windows 10?

**Comment by mrmoss** [comment]
Alright, I think I see it. I can only get it to reproduce if one I start on
Helloworld and go to something else.

**Comment by Michaeasmith** [comment]
On Windows 10. I reproduced it just now on Chrome, Firefox, and Edge.

**Comment by mrmoss** [comment]
So I just pushed a pretty major change...could I get multiple testers on
this before I close it since it's a pretty important part? @olawlor @arsh25
@Michaeasmith @FineTralfazz

**Comment by Arsh25** [comment]
@mrmoss any steps to reproduce the issue?

**Comment by mrmoss** [comment]
It shouldn't be reproducible at all. Just try and break it?

**Comment by FineTralfazz** [comment]
Latest version is running on test.robotmoose.com. I'll start messing with it.

**Comment by mrmoss** [comment]
I'm actually more worried that I broke other things...

**Comment by FineTralfazz** [comment]
The code upload feature is gone. Not sure if that was intentional or not.

**Comment by mrmoss** [comment]
Do you mean the load file button? I just added that back in if so.

**Comment by mrmoss** [comment]
And the load file stuff is broken...fixing now.

**Comment by mrmoss** [comment]
Fixed.

**Comment by Arsh25** [comment]
Hitting new and then using `esc` to quit the dialogue freezes the whole frontend

**Comment by mrmoss** [comment]
Not frozen, if you inspect the page, the modal is still there, just invisible...I think that's a bug with the modal class.

**Comment by mrmoss** [comment]
@arsh25 Modal stuff should be fixed now.

**Comment by Arsh25** [comment]
Verified modal fix

**Comment by mrmoss** [comment]
Well, I guess I'll close this...?
